resolver: lts-7.0
extra-deps:
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- hackage-security-HTTP-0.1.1
image:
  containers:
  - name: snoyberg/hackage-mirror-tool
    base: fpco/stack-run:lts-7
    add:
      etc: /usr/local/bin/
